trigger: none

pool:
 vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: build_job
        steps:
        - task: Npm@1
          displayName: npm install for dependency
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)'
        
        - task: Npm@1
          displayName: npm build
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: 'run build'

  
        - task: PublishPipelineArtifact@1
          displayName: build upload
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/build'
            artifact: 'todo-build'
            publishLocation: 'pipeline'

  - stage: deploy
    jobs:
      - job: deployemet_job
        steps:
        - task: DownloadBuildArtifacts@1
          displayName: download artifacts
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'todo-build'
            downloadPath: '$(System.ArtifactsDirectory)'
            cleanDestinationFolder: true

        - task: CopyFilesOverSSH@0
          displayName: copy artifatcs
          inputs:
            sshEndpoint: 'devvmc'
            sourceFolder: '$(System.ArtifactsDirectory)'
            contents: '**'
            targetFolder: '/tmp'
            readyTimeout: '20000'

        - task: SSH@0
          inputs:
            sshEndpoint: 'devvmc'
            runOptions: 'commands'
            commands: 'sudo cp -r /tmp/* /var/www/html'
            readyTimeout: '20000'